# Site settings
title: code, music and rants
description: Thoughts, stories and ideas.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: ricdros
github_username:  missingcharacter
repository: "missingcharacter/ricdros.com"
minimal_mistakes_skin: default
search: true
analytics:
  provider: "custom"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
#theme: minima
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: Etc/UTC

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Ricardo Rosales"
  bio    : "Thoughts, stories and ideas."
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://ricdros.com"
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/ricdros"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/missingcharacter"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-twitter"
      url: "https://twitter.com/ricdros"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/missingcharacter"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
